# Generated by Django 4.1.7 on 2023-03-09 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='quality',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='orderplaced',
            old_name='producxt',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='orderplaced',
            old_name='quality',
            new_name='quantity',
        ),
    ]
